name: Parse deps block
description: >
  Parses the ```deps block from a PR body, resolves refs, and outputs
  an extra-packages list for setup-r-dependencies plus (optionally) a
  git ref for a specific package.

inputs:
  pr-body:
    description: The pull request body text.
    required: true
  pkg:
    description: >
      If set, also extract the git ref for this specific package
      (owner/repo). Used by the revdep workflow.
    required: false
    default: ''
  base-packages:
    description: >
      Newline-separated pak refs to prepend to extra-packages before
      appending the deps block entries. Defaults to any::rcmdcheck.
    required: false
    default: any::rcmdcheck

outputs:
  extra-packages:
    description: Newline-separated pak refs for setup-r-dependencies.
    value: ${{ steps.parse.outputs.extra-packages }}
  ref:
    description: Git ref for the requested package, empty if not found.
    value: ${{ steps.parse.outputs.ref }}

runs:
  using: composite
  steps:
    - name: Parse
      id: parse
      shell: bash
      env:
        PR_BODY: ${{ inputs.pr-body }}
        PKG: ${{ inputs.pkg }}
        BASE_PACKAGES: ${{ inputs.base-packages }}
      run: ${{ github.action_path }}/parse-deps.sh
