name: Parse deps block
description: >
  Parses the ```deps block from a PR body, resolves refs, and outputs
  an extra-packages list for setup-r-dependencies plus (optionally) a
  git ref for a specific package.

inputs:
  pr-body:
    description: The pull request body text.
    required: true
  pkg:
    description: >
      If set, also extract the git ref for this specific package
      (owner/repo). Used by the revdep workflow.
    required: false
    default: ''
  base-packages:
    description: >
      Newline-separated pak refs to prepend to extra-packages before
      appending the deps block entries. Defaults to any::rcmdcheck.
    required: false
    default: any::rcmdcheck
  description-path:
    description: >
      Path to a DESCRIPTION file. If set, internal dependencies are
      resolved via the package registry and added to extra-packages.
    required: false
    default: ''
  default-deps:
    description: >
      Newline-separated pak refs to include in extra-packages.
      These override registry entries but are overridden by PR body deps.
    required: false
    default: ''

outputs:
  extra-packages:
    description: Newline-separated pak refs for setup-r-dependencies.
    value: ${{ steps.parse.outputs.extra-packages }}
  ref:
    description: Git ref for the requested package, empty if not found.
    value: ${{ steps.parse.outputs.ref }}

runs:
  using: composite
  steps:
    - name: Parse
      id: parse
      shell: bash
      env:
        PR_BODY: ${{ inputs.pr-body }}
        PKG: ${{ inputs.pkg }}
        BASE_PACKAGES: ${{ inputs.base-packages }}
        DESCRIPTION_PATH: ${{ inputs.description-path }}
        DEFAULT_DEPS: ${{ inputs.default-deps }}
        REGISTRY: ${{ github.action_path }}/../registry.txt
        SCRIPT_DIR: ${{ github.action_path }}
      run: bash "$SCRIPT_DIR/parse-deps.sh"
