name: Re-run deps-affected jobs
description: >
  Compares the ```deps block between two PR body versions and, if it
  changed, re-runs all jobs in the most recent CI run for the given
  SHA whose names match job-pattern.

inputs:
  old-body:
    description: Previous PR body (github.event.changes.body.from).
    required: true
  new-body:
    description: Current PR body (github.event.pull_request.body).
    required: true
  sha:
    description: Head SHA of the pull request.
    required: true
  repo:
    description: Repository in owner/repo form.
    required: true
  token:
    description: GitHub token with actions:write permission.
    required: true
  job-pattern:
    description: Extended-regex pattern matched against job names.
    required: false
    default: (lint|smoke|revdep)

runs:
  using: composite
  steps:
    - name: Check if deps block changed
      id: deps-diff
      shell: bash
      env:
        OLD_BODY: ${{ inputs.old-body }}
        NEW_BODY: ${{ inputs.new-body }}
      run: ${{ github.action_path }}/deps-diff.sh

    - name: Re-run affected jobs
      if: steps.deps-diff.outputs.changed == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        SHA: ${{ inputs.sha }}
        REPO: ${{ inputs.repo }}
        JOB_PATTERN: ${{ inputs.job-pattern }}
      run: |
        RUN_ID=$(gh run list \
          --repo "$REPO" \
          --workflow ci.yaml \
          --json databaseId,headSha,createdAt \
          --jq "[.[] | select(.headSha == \"$SHA\")] | sort_by(.createdAt) | last | .databaseId")

        if [ -z "$RUN_ID" ] || [ "$RUN_ID" = "null" ]; then
          echo "No CI run found for SHA $SHA"
          exit 1
        fi

        echo "Looking for jobs matching '$JOB_PATTERN' in run $RUN_ID"

        JOBS=$(gh api "repos/$REPO/actions/runs/$RUN_ID/jobs" --paginate \
          --jq ".jobs[] | select(.name | test(\"$JOB_PATTERN\")) | \"\(.id) \(.name)\"")

        if [ -z "$JOBS" ]; then
          echo "No matching jobs found. Available jobs:"
          gh api "repos/$REPO/actions/runs/$RUN_ID/jobs" --paginate \
            --jq '.jobs[] | "  \(.name)"'
          exit 1
        fi

        echo "$JOBS" | while read -r JOB_ID JOB_NAME; do
          echo "Re-running job $JOB_ID ($JOB_NAME)"
          gh api "repos/$REPO/actions/jobs/$JOB_ID/rerun" --method POST 2>&1 || true
        done
