name: Re-run deps-affected jobs
description: >
  Compares the ```deps block between two PR body versions and, if it
  changed, re-runs all jobs in the most recent CI run for the given
  SHA whose names match job-pattern.

inputs:
  old-body:
    description: Previous PR body (github.event.changes.body.from).
    required: true
  new-body:
    description: Current PR body (github.event.pull_request.body).
    required: true
  sha:
    description: Head SHA of the pull request.
    required: true
  repo:
    description: Repository in owner/repo form.
    required: true
  token:
    description: GitHub token with actions:write permission.
    required: true
  job-pattern:
    description: Extended-regex pattern matched against job names.
    required: false
    default: ^(smoke|revdep)

runs:
  using: composite
  steps:
    - name: Check if deps block changed
      id: deps-diff
      shell: bash
      env:
        OLD_BODY: ${{ inputs.old-body }}
        NEW_BODY: ${{ inputs.new-body }}
      run: |
        extract_deps() {
          echo "$1" | tr -d '\r' \
            | sed -n '/^```deps$/,/^```$/p' \
            | grep -v '^```' \
            | sort
        }
        if [ "$(extract_deps "$OLD_BODY")" = "$(extract_deps "$NEW_BODY")" ]; then
          echo "changed=false" >> "$GITHUB_OUTPUT"
        else
          echo "changed=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Re-run affected jobs
      if: steps.deps-diff.outputs.changed == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
        SHA: ${{ inputs.sha }}
        REPO: ${{ inputs.repo }}
        JOB_PATTERN: ${{ inputs.job-pattern }}
      run: |
        RUN_ID=$(gh run list \
          --repo "$REPO" \
          --workflow ci.yaml \
          --json databaseId,headSha,createdAt \
          --jq "[.[] | select(.headSha == \"$SHA\")] | sort_by(.createdAt) | last | .databaseId")

        if [ -z "$RUN_ID" ] || [ "$RUN_ID" = "null" ]; then
          echo "No CI run found for SHA $SHA"
          exit 1
        fi

        gh api "repos/$REPO/actions/runs/$RUN_ID/jobs" --paginate \
          --jq ".jobs[] | select(.name | test(\"$JOB_PATTERN\")) | .id" \
        | while read -r JOB_ID; do
          gh api "repos/$REPO/actions/jobs/$JOB_ID/rerun" --method POST
        done
